import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const owner = '11111111-1111-4111-8111-111111111111', reviewer = '22222222-2222-4222-8222-222222222222', stranger = '33333333-3333-4333-8333-333333333333';
const project = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', snapshot = 'a'.repeat(64);
test('PostgreSQL permissions enforce invitations, immutable anchors and optimistic updates', async t => {
  const db = new PGlite();
  try {
    await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); grant usage on schema auth to authenticated, anon; create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims', true), ''), '{}')::jsonb; $$; create function auth.uid() returns uuid language sql stable as $$ select (auth.jwt()->>'sub')::uuid; $$;`);
    await db.exec(await readFile(new URL('../database/schema.sql', import.meta.url), 'utf8'));
    for (const id of [owner, reviewer, stranger]) await db.query('insert into auth.users values ($1)', [id]);
    const as = async (id, email, fn, role = 'authenticated') => { await db.query("select set_config('request.jwt.claims', $1, false)", [JSON.stringify({ sub: id, email, role })]); await db.exec('set role ' + role); try { return await fn(); } finally { await db.exec('reset role'); } };
    const notebook = { nbformat: 4, cells: [{ id: 'intro', cell_type: 'markdown', source: 'hello' }, { cell_type: 'markdown', source: 'legacy' }] };
    await t.test('owner creates own project; cannot spoof ownership', async () => { await as(owner, 'owner@example.org', () => db.query('insert into public.review_projects(id,owner_id,title,base_notebook,snapshot_id) values($1,$2,$3,$4,$5)', [project,owner,'Review',notebook,snapshot])); await assert.rejects(as(reviewer,'reviewer@example.org',()=>db.query('insert into public.review_projects(owner_id,title,base_notebook,snapshot_id) values($1,$2,$3,$4)',[owner,'fake',notebook,snapshot]))); });
    await t.test('anonymous and nonmembers cannot read projects or comments', async () => { for (const role of ['anon','authenticated']) { const read = as(stranger,'stranger@example.org',()=>db.query('select * from public.review_projects'),role); if (role==='anon') await assert.rejects(read); else assert.equal((await read).rows.length,0); } });
    await t.test('only owner can grant membership', async () => { await assert.rejects(as(stranger,'stranger@example.org',()=>db.query('insert into public.review_members values($1,$2,now())',[project,'stranger@example.org']))); await as(owner,'owner@example.org',()=>db.query('insert into public.review_members(project_id,email) values($1,$2)',[project,'reviewer@example.org'])); });
    await t.test('invited reviewer reads snapshot but cannot update it', async () => { assert.equal((await as(reviewer,'reviewer@example.org',()=>db.query('select * from public.review_projects'))).rows.length,1); assert.equal((await as(reviewer,'reviewer@example.org',()=>db.query("update public.review_projects set title='hijack' where id=$1 returning *",[project]))).rows.length,0); });
    let commentId;
    await t.test('reviewer comment identity is derived from authenticated email', async () => { const result=await as(reviewer,'reviewer@example.org',()=>db.query('insert into public.review_comments(project_id,author_id,author_email,cell_key,snapshot_id,body) values($1,$2,$3,$4,$5,$6) returning *',[project,reviewer,'spoofed@example.org','id:intro',snapshot,'Please explain'])); commentId=result.rows[0].id; assert.equal(result.rows[0].author_email,'reviewer@example.org'); });
    await t.test('invalid cell, wrong snapshot and spoofed author are rejected', async () => { for (const [author,key,snap] of [[reviewer,'id:missing',snapshot],[reviewer,'id:intro','b'.repeat(64)],[owner,'id:intro',snapshot]]) await assert.rejects(as(reviewer,'reviewer@example.org',()=>db.query('insert into public.review_comments(project_id,author_id,cell_key,snapshot_id,body) values($1,$2,$3,$4,$5)',[project,author,key,snap,'bad']))); });
    await t.test('legacy cell index is accepted',async()=>{ await as(reviewer,'reviewer@example.org',()=>db.query('insert into public.review_comments(project_id,author_id,cell_key,snapshot_id,body) values($1,$2,$3,$4,$5)',[project,reviewer,'legacy:1',snapshot,'Legacy comment'])); });
    await t.test('owner cannot rewrite a reviewer comment or reanchor it',async()=>{ await assert.rejects(as(owner,'owner@example.org',()=>db.query("update public.review_comments set body='rewritten' where id=$1",[commentId]))); await assert.rejects(as(reviewer,'reviewer@example.org',()=>db.query("update public.review_comments set cell_key='legacy:1' where id=$1",[commentId]))); });
    await t.test('owner can resolve, stale version update is rejected by predicate',async()=>{ const result=await as(owner,'owner@example.org',()=>db.query('update public.review_comments set resolved=true where id=$1 and version=1 returning *',[commentId])); assert.equal(result.rows[0].version,2); assert.equal((await as(reviewer,'reviewer@example.org',()=>db.query('update public.review_comments set resolved=false where id=$1 and version=1 returning *',[commentId]))).rows.length,0); });
    await t.test('project baseline and owner are immutable',async()=>{ await assert.rejects(as(owner,'owner@example.org',()=>db.query('update public.review_projects set snapshot_id=$1 where id=$2',['b'.repeat(64),project]))); await assert.rejects(as(owner,'owner@example.org',()=>db.query('update public.review_projects set owner_id=$1 where id=$2',[reviewer,project]))); });
    await t.test('owner can upload revised notebook',async()=>{ const result=await as(owner,'owner@example.org',()=>db.query('update public.review_projects set revision_notebook=$1 where id=$2 returning *',[notebook,project])); assert.equal(result.rows[0].version,2); });
    await t.test('revision acknowledgement only accepts the current version',async()=>{ await assert.rejects(as(owner,'owner@example.org',()=>db.query('update public.review_comments set reviewed_revision_version=99 where id=$1',[commentId])));const result=await as(owner,'owner@example.org',()=>db.query('update public.review_comments set resolved=true,reviewed_revision_version=2 where id=$1 returning *',[commentId]));assert.equal(result.rows[0].reviewed_revision_version,2); });
    await t.test('new revisions retain the older acknowledgement; reopening clears it',async()=>{await as(owner,'owner@example.org',()=>db.query('update public.review_projects set revision_notebook=$1 where id=$2',[notebook,project]));const older=await as(owner,'owner@example.org',()=>db.query('select * from public.review_comments where id=$1',[commentId]));assert.equal(older.rows[0].reviewed_revision_version,2);const reopened=await as(reviewer,'reviewer@example.org',()=>db.query('update public.review_comments set resolved=false where id=$1 returning *',[commentId]));assert.equal(reopened.rows[0].reviewed_revision_version,null);});
    await t.test('additive migration preserves comments and may safely be reapplied',async()=>{const before=await db.query('select count(*)::int as n from public.review_comments');await db.exec('alter table public.review_comments drop column reviewed_revision_version');await db.exec(await readFile(new URL('../database/migrate-v2.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../database/migrate-v2.sql',import.meta.url),'utf8'));assert.equal((await db.query('select count(*)::int as n from public.review_comments')).rows[0].n,before.rows[0].n);});
    await t.test('cloud migration retains data, permissions and unrelated publications', async()=>{
      const before=await db.query('select count(*)::int as n from public.review_comments');
      await db.exec('create table public.unrelated(id integer); create publication supabase_realtime for table public.unrelated;');
      const migration=await readFile(new URL('../supabase/migrations/20261009000200_review_realtime.sql',import.meta.url),'utf8');
      await db.exec(migration); await db.exec(migration);
      assert.equal((await db.query('select count(*)::int as n from public.review_comments')).rows[0].n,before.rows[0].n);
      const tables=(await db.query("select tablename from pg_publication_tables where pubname='supabase_realtime' order by tablename")).rows.map(r=>r.tablename);
      assert.deepEqual(tables,['review_comments','review_projects','unrelated']);
      assert.equal((await as(stranger,'stranger@example.org',()=>db.query('select * from public.review_comments'))).rows.length,0);
      await assert.rejects(as(reviewer,'reviewer@example.org',()=>db.query('select public.review_comment_guard()')));
    });
    await t.test('revoking invitation removes read and write access immediately',async()=>{ await as(owner,'owner@example.org',()=>db.query('delete from public.review_members where project_id=$1 and email=$2',[project,'reviewer@example.org'])); assert.equal((await as(reviewer,'reviewer@example.org',()=>db.query('select * from public.review_comments'))).rows.length,0); await assert.rejects(as(reviewer,'reviewer@example.org',()=>db.query('insert into public.review_comments(project_id,author_id,cell_key,snapshot_id,body) values($1,$2,$3,$4,$5)',[project,reviewer,'id:intro',snapshot,'after revocation']))); });
  } finally { await db.close(); }
});
