import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
const url=process.argv[2];if(!url)throw new Error('Usage: node scripts/smoke.mjs https://owner.github.io/repository/');
const browser=await chromium.launch({channel:'chromium',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(new URL(url).origin))failed.push({url:r.url(),status:r.status()});});
 const start=performance.now();await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});assert.equal(await page.locator('html').getAttribute('lang'),'en');await expect(page.locator('#mode')).toContainText(/Local demo|Sign in to share/);await page.getByRole('button',{name:'Open example review →'}).click();await page.locator('#cell-1').getByRole('button',{name:'Discuss',exact:true}).click();await page.getByLabel('Your feedback').fill('Deployment check: explain the missing sample');await page.getByRole('button',{name:'Post feedback'}).click();await page.locator('.comment').waitFor();await page.getByRole('button',{name:'Mark resolved'}).click();await page.getByRole('button',{name:'See example changes',exact:true}).click();await page.getByRole('button',{name:'Confirm revision reviewed',exact:true}).waitFor();assert.match(await page.locator('#comments').innerText(),/Revision needs review/);await page.getByRole('button',{name:'Confirm revision reviewed',exact:true}).click();assert.doesNotMatch(await page.locator('#comments').innerText(),/Revision needs review/);await page.locator('#cell-1 summary').click();assert.match(await page.locator('#cell-1 .line-diff').innerText(),/instrument/);const config=await page.evaluate(async()=>await(await fetch(new URL('./config.json',location.href))).json());assert.equal(typeof config.configured,'boolean');assert.equal(await page.getByRole('button',{name:'Sign in with email',exact:true}).count(),config.configured?1:0);await page.screenshot({path:'evidence/deployed-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Back to selected cell ↑'}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'evidence/deployed-mobile.png',fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 console.log(JSON.stringify({url:page.url(),config:config.configured?'frontend configured; backend not exercised':'local demo',task:'open, comment, resolve, compare, acknowledge, line diff, mobile',elapsedMs:Math.round(performance.now()-start),pageErrors:errors,httpErrors:failed}));
}finally{await browser.close();}
