import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
const url=process.argv[2];if(!url)throw new Error('Usage: node scripts/smoke.mjs https://owner.github.io/repository/');
const browser=await chromium.launch({channel:'chromium',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(new URL(url).origin))failed.push({url:r.url(),status:r.status()});});
 const start=performance.now();await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await expect(page.locator('#mode')).toContainText('本地演示');await page.getByRole('button',{name:'打开示例审阅 →'}).click();await page.locator('#cell-1').getByRole('button',{name:'讨论',exact:true}).click();await page.getByLabel('你的反馈').fill('部署验收：请说明缺失样本');await page.getByRole('button',{name:'发送反馈'}).click();await page.locator('.comment').waitFor();await page.getByRole('button',{name:'标记已处理'}).click();await page.getByRole('button',{name:'查看示例修改',exact:true}).click();await page.getByRole('button',{name:'确认已核对新版',exact:true}).waitFor();assert.match(await page.locator('#comments').innerText(),/新版需复核/);await page.getByRole('button',{name:'确认已核对新版',exact:true}).click();assert.doesNotMatch(await page.locator('#comments').innerText(),/新版需复核/);await page.locator('#cell-1 summary').click();assert.match(await page.locator('#cell-1 .line-diff').innerText(),/仪器/);const config=await page.evaluate(async()=>await(await fetch(new URL('./config.json',location.href))).json());assert.equal(config.configured,false,'This demo smoke requires an unconfigured static deployment; use the live Auth checklist for configured deployments.');assert.equal(await page.getByRole('button',{name:'邮箱登录',exact:true}).count(),0);await page.screenshot({path:'evidence/deployed-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'返回当前单元格 ↑'}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'evidence/deployed-mobile.png',fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 console.log(JSON.stringify({url:page.url(),config:config.configured?'online':'local demo',task:'open, comment, resolve, compare, acknowledge, line diff, mobile',elapsedMs:Math.round(performance.now()-start),pageErrors:errors,httpErrors:failed}));
}finally{await browser.close();}
